add enable/disable to domtool and update usage

diff --git a/domtool b/domtool
--- a/domtool
+++ b/domtool
@@ -20,26 +20,28 @@
 # shellcheck disable=SC2034,SC2129
 
 SCHED_CONFIG="/etc/xen/sched.conf"
-VERSION=0.01
+VERSION=0.02
 
 usage(){
 	printf "Usage: %s COMMAND [OPTION]...\n" "$PROGRAM"
 	printf "xen hypervisor helper (basically a wrapper for xl and xen-tools)\n\n"
 	printf "Commands:\n"
-	printf "  create [CONFIG_FILE]                create new DOMU interactively or from CONFIG_FILE\n"
-	printf "  erase DOMU                          delete DOMU, removing configs and destroying disks\n"
-	printf "  help                                print this usage\n"
-	printf "  restart DOMU                        restart DOMU\n"
-	printf "  schedule {add...|remove...|update}  modify cpu scheduler\n"
-	printf "      add DOMU VALUE                  add DOMU with VALUE weight (calls update)\n"
-	printf "      remove DOMU                     removes DOMU from %s\n" "SCHED_CONFIG"
-	printf "      update                          update running DOMUs with weights specified in:\n"
-	printf "                                       %s\n" "$SCHED_CONFIG"
+	printf "  \e[1mcreate\e[0m [CONFIG_FILE]                  create new \e[1mDOMU\e[0m interactively or from CONFIG_FILE\n"
+	printf "  \e[1mdisable\e[0m|\e[1menable\e[0m DOMU                   enable or disable \e[1mDOMU\e[0m from starting on host boot\n"
+	printf "  \e[1merase\e[0m DOMU                            delete \e[1mDOMU\e[0m, removing configs and destroying disks\n"
+	printf "  \e[1mhelp\e[0m                                  print this usage\n"
+	printf "  \e[1mrestart\e[0m DOMU                          restart \e[1mDOMU\e[0m\n"
+	printf "  \e[1mschedule\e[0m {\e[1madd\e[0m...|\e[1mremove\e[0m...|\e[1mupdate\e[0m}    modify cpu scheduler\n"
+	printf "      \e[1madd\e[0m DOMU VALUE                    add \e[1mDOMU\e[0m with VALUE weight (calls update)\n"
+	printf "      \e[1mremove\e[0m DOMU                       removes \e[1mDOMU\e[0m from %s\n" "SCHED_CONFIG"
+	printf "      \e[1mupdate\e[0m                            update running \e[1mDOMUs\e[0m with weights specified in:\n"
+	printf "                                         %s\n" "$SCHED_CONFIG"
 	printf "Options:\n"
-	printf "  -v, --verbose        be verbose in output (add more for more verbosity)\n"
-	printf "  -V, --version        show version and exit\n"
-	printf "  -f, --force          force execute the command\n"
-	printf "  -h, --help           specific command help\n"
+	printf "  \e[1m-v\e[0m,\e[1m --verbose\e[0m        be verbose in output (add more for more verbosity)\n"
+	printf "  \e[1m-V\e[0m,\e[1m --version\e[0m        show version and exit\n"
+	printf "  \e[1m-f\e[0m,\e[1m --force\e[0m          force execute the command\n"
+	printf "  \e[1m-h\e[0m,\e[1m --help\e[0m           specific command help\n"
+	printf "  \e[1m-e\e[0m,\e[1m --enable\e[0m         enable DOMU on host boot (only used with create - default is disable)\n"
 	exit
 }
 
@@ -221,6 +223,9 @@ create_dom(){
 		sleep 1
 	done
 	update_sched add "$DOMNAME" "$CREDIT"
+	if [ "ENABLE" == "1" ];then
+		ed_dom enable "$DOMNAME"
+	fi
 	ENDTIME="$(date +%s)"
 	TOTALTIME=$((ENDTIME-STARTTIME))
 	TOTALTIME="$(date -d@$TOTALTIME -u +%H:%M:%S)"
@@ -328,11 +333,46 @@ restart_dom(){
 	if [ "$VERBOSE" -ge "1" ];then printf "\e[38;2;0;255;0m[+]\e[0m script time: %s\n" "$TOTALTIME";fi
 }
 
+ed_dom(){
+	if [ -z "$1" ] || [ -z "$2" ];then
+		>&2 printf "\e[38;2;255;0;0m[!]\e[0m usage: %s enable|disable DOMU\n" "$PROGRAM"
+		exit 1
+	fi
+	if [ "$(check_exist "$2")" == "1" ];then
+		>&2 printf "\e[38;2;255;0;0m[!]\e[0m DOMU specified not found\n"
+		exit 1
+	fi
+	if [ "$(file /etc/xen/auto|awk '{print $2}')" != "directory" ];then
+		if [ "$VERBOSE" -ge "1" ];then printf "\e[38;2;0;255;0m[+]\e[0m /etc/xen/auto is not a directory. Delete and make it a dir\n";fi
+		return
+		# !TODO: add logic to enable all machines in auto
+		rm -rf /etc/xen/auto
+		mkdir -p /etc/xen/auto
+	fi
+	if [ "$1" == "enable" ];then
+		if [ "$VERBOSE" -ge "1" ];then printf "\e[38;2;0;255;0m[+]\e[0m Creating symlink\n";fi
+		ln -sf /etc/xen/"$2".cfg /etc/xen/auto/
+		if [ "$VERBOSE" -ge "1" ];then printf "\e[38;2;0;255;0m[+]\e[0m Writing config\n";fi
+		SCHD="$(grep "$2" "$SCHED_CONFIG"|awk '{print $2}')"
+		sed -i "$(grep -n "$2" < "$SCHED_CONFIG"| tr ':' ' ' | awk '{print $1}' | head -1)s/.*/$2\t$SCHD\t1/" "$SCHED_CONFIG"
+	elif [ "$1" == "disable" ];then
+		if [ "$VERBOSE" -ge "1" ];then printf "\e[38;2;0;255;0m[+]\e[0m Removing symlink\n";fi
+		rm -rf /etc/xen/auto/"$2".cfg
+		if [ "$VERBOSE" -ge "1" ];then printf "\e[38;2;0;255;0m[+]\e[0m Writing config\n";fi
+		SCHD="$(grep "$2" "$SCHED_CONFIG"|awk '{print $2}')"
+		sed -i "$(grep -n "$2" < "$SCHED_CONFIG"| tr ':' ' ' | awk '{print $1}' | head -1)s/.*/$2\t$SCHD\t0/" "$SCHED_CONFIG"
+	fi
+	if [ "$VERBOSE" -ge "2" ];then
+		cat "$SCHED_CONFIG"
+	fi
+}
+
 PROGRAM="${0##*/}"
 VERBOSE=0
 HELP=0
 FORCE=0
-opts="$(getopt -o vVfh -l version,help,verbose,force -n "$PROGRAM" -- "$@" 2>/dev/null)"
+ENABLE=0
+opts="$(getopt -o evVfh -l enable,version,help,verbose,force -n "$PROGRAM" -- "$@" 2>/dev/null)"
 err=$?
 if [ $err -ne 0 ];then
 	usage
@@ -341,6 +381,7 @@ fi
 eval set -- "$opts"
 while true; do case $1 in
 	-f|--force) FORCE=1; shift ;;
+	-e|--enable) ENABLE=1; shift ;;
 	-h|--help) HELP=1; shift ;;
 	-v|--verbose) VERBOSE=$((VERBOSE+1)); shift ;;
 	-V|--version) show_ver ;;
@@ -356,6 +397,7 @@ if [ "$EUID" -ne 0 ];then
 fi
 
 case "$1" in
+	disable|enable)		ed_dom "$@";;
 	erase) shift;		erase_dom "$@" ;;
 	restart) shift;		restart_dom "$@" ;;
 	create) shift;		create_dom "$@" ;;
