fix sig wipe on tmplvm, add rsync options, and add tar options note that both the rsync and tar options have not been tested in production - only in test environments

diff --git a/sync b/sync
--- a/sync
+++ b/sync
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+echo "!TODO: add logfile"
+
 DAYSTHRESH=15
 DEVICE="$1"
 NAME="$2"
@@ -23,7 +25,7 @@ if [ -z "$NAME" ];then
 fi
 TMP="$(udevadm info --query=all --name="$DEVICE" 2> /dev/null|grep "N:")"
 if [ -z "$TMP" ];then
-	>&2 printf "\e[38;2;255;0;0m[!]\e[0m %s Does not exist on the system\n" "$DEVICE"
+	>&2 printf "\e[38;2;255;0;0m[!]\e[0m %s does not exist on the system\n" "$DEVICE"
 	exit 1
 fi
 TMP="$(lsblk --ascii --fs "$DEVICE"|head -2|tail -1|grep crypto_LUKS|awk '{print $1}'|tr -d '`-')"
@@ -43,33 +45,28 @@ sigint() {
 }
 cleaner(){
 	#Added Sleeps here to give time to umount and such (I may have to add -l to umount, but who knows)
-	printf "\e[38;2;0;255;255m [-]\e[0m Cleaning up mounted directories\n"
+	printf "\e[38;2;0;255;255m [-]\e[0m Cleaning mounted devices\n"
 	sync 2> /dev/null
 	sleep 1
 	umount /media/tmp 2> /dev/null
 	sleep 1
 	lvchange -an /dev/vg0/tmplvm 2> /dev/null
 	sleep 1
-	lvremove /dev/vg0/tmplvm -y 2> /dev/null
+	lvremove /dev/vg0/tmplvm -y > /dev/null 2>&1
 	sleep 1
 	umount /media/backupspot 2> /dev/null
 	sleep 1
-	vgchange -a n /dev/"$NAME"vg 2> /dev/null
+	vgchange -a n /dev/"$NAME"vg > /dev/null 2>&1
 	sleep 1
 	cryptsetup luksClose "$NAME" 2> /dev/null
 	printf "\e[38;2;0;255;255m [-]\e[0m Done\n"
 }
-end(){
-	sleep 1
-	echo "poweroff drive"
-	# udisksctl power-off -b "$DEVICE"
-}
 
 trap 'sigint' SIGINT
 cryptsetup luksOpen "$DEVICE" "$NAME"
-STARTTIME="$(date +%s)"
 printf "\e[38;2;0;255;0m[+]\e[0m Setting up script\n"
 sleep 5
+STARTTIME="$(date +%s)"
 mkdir -p /media/backupspot
 umount -l /media/backupspot 2> /dev/null
 printf "\e[38;2;0;255;255m [-]\e[0m Mounting %s on /media/backupspot\n" "$NAME"
@@ -90,26 +87,24 @@ else
 fi
 mkdir -p /media/backupspot/"$BACKUPDIR"
 
-
-
-
-
-
-
+# Keep this for a bit to test that the auto dir naming works
 echo "making /media/backupspot/$BACKUPDIR"
 read -p "continue? " CONT
 
 
-
-
-
-
 printf "\e[38;2;0;255;255m [-]\e[0m Creating temporary filesystem\n"
-lvcreate -L 500G -n tmplvm vg0 --wipesignatures y 2> /dev/null
-mkfs.ext4 /dev/vg0/tmplvm -F 2> /dev/null
+lvcreate -W y -L 500G -n tmplvm vg0 -y > /dev/null 2>&1
+mkfs.ext4 /dev/vg0/tmplvm -F > /dev/null 2>&1
 mkdir -p /media/tmp
 printf "\e[38;2;0;255;255m [-]\e[0m Mounting temporary filesystem\n"
 mount /dev/vg0/tmplvm /media/tmp
+TMP="$(lsblk|grep /media/tmp)"
+if [ -z "$TMP" ];then
+	>&2 printf "\e[38;2;255;0;0m[!]\e[0m Failed to create or mount temporary filesystem\n"
+	cleaner
+	exiter 1
+fi
+
 DOMS="$(xl list | awk '{if(NR>2)print $1}')"
 printf "\e[38;2;0;255;0m[+]\e[0m Start backup\n"
 for i in $DOMS;do
@@ -124,7 +119,7 @@ for i in $DOMS;do
 		sleep 1
 		COUNTER=$((COUNTER + 1))
 		if [ $COUNTER -gt 300 ];then
-			>&2 printf "\e[38;2;255;0;0m[!]\e[0m %s Failed to shut down in a timely manner\n" "$i"
+			>&2 printf "\e[38;2;255;0;0m[!]\e[0m %s failed to shut down in a timely manner\n" "$i"
 			>&2 printf "\e[38;2;255;0;0m[!]\e[0m Destroying %s\n" "$i"
 			xl destroy "$i"
 			break
@@ -134,46 +129,45 @@ for i in $DOMS;do
 	mount /dev/vg0/"$i"-disk /mnt/
 	printf "\e[38;2;0;0;255m  [*]\e[0m Backing up %s\n" "$i"
 	mkdir -p /media/tmp/"$i"
-	rsync -aAX --exclude={"dev/*","proc/*","sys/*","tmp/*","run/*","mnt/*","media/*","lost+found","swap.img"} /mnt/ /media/tmp/"$i"
+	rsync -aAHXWS --numeric-ids --exclude={"dev/*","proc/*","sys/*","tmp/*","run/*","mnt/*","media/*","lost+found","swap.img"} /mnt/ /media/tmp/"$i"
 	umount /mnt
 	printf "\e[38;2;0;0;255m  [*]\e[0m Reactivating vm %s\n" "$i"
 	xl create /etc/xen/"$i".cfg 2> /dev/null
-	# Need to check if vm actually started here:
-
 	if [ ! -d "/media/tmp/$i" ]; then
-		>&2 printf "\e[38;2;255;0;0m[!]\e[0m Could not cd to \"/media/tmp/%s\". Exiting.\n" "$i"
+		>&2 printf "\e[38;2;255;0;0m[!]\e[0m /media/tmp/%s does not exist. Exiting.\n" "$i"
 		cleaner
 		exiter 1
 	fi
 	cd /media/tmp/"$i" 2>/dev/null|| exiter
 	printf "\e[38;2;0;0;255m  [*]\e[0m Compressing %s data to %s on /media/backupspot/$BACKUPDIR\n" "$i" "$DEVICE"
-	tar -czf /media/backupspot/"$BACKUPDIR"/"$i".tar.gz -- *
+	tar --atime-preserve --xattrs --acls --numeric-owner -pczfS /media/backupspot/"$BACKUPDIR"/"$i".tar.gz -- *
 	touch -am /media/backupspot/"$BACKUPDIR"/"$i".tar.gz
 	if [ "$(du /media/backupspot/"$BACKUPDIR"/"$i".tar.gz | awk '{print $1}')" -gt 200000000 ];then
-		# Should remove the source for the tarball here to save space. (check that it copied completely and then remove it)
+		# Remove the source for the tarball here to save space. (check that it copied completely and then remove it)
+				date +%s			# this is just for me to see timing (it may be faster to just unmount the filesystem and create new)
 		cd /media/tmp 2>/dev/null|| exiter
 		mkdir empty_dir
 		rsync -a --delete empty_dir/ "$i"/
 		rm -rf empty_dir "$i"
+				date +%s
 	fi
 done
-printf "\e[38;2;0;255;255m [-]\e[0m vmhost\n"
+printf "\e[38;2;0;255;255m [-]\e[0m vmhost:\n"
 mkdir -p /media/tmp/vmhost
 printf "\e[38;2;0;0;255m  [*]\e[0m Backing up vmhost\n"
-rsync -aAX / --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found","/swap.img"} /media/tmp/vmhost
+rsync -aAHXWS --numeric-ids / --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found","/swap.img"} /media/tmp/vmhost
 if [ ! -d "/media/tmp/vmhost" ]; then
-	>&2 printf "\e[38;2;255;0;0m[!]\e[0m Could not cd to /media/tmp/vmhost. Exiting.\n"
+	>&2 printf "\e[38;2;255;0;0m[!]\e[0m /media/tmp/vmhost does not exist. Exiting.\n"
 	cleaner
 	exiter 1
 fi
 cd /media/tmp/vmhost 2>/dev/null|| exiter
 printf "\e[38;2;0;0;255m  [*]\e[0m Compressing vmhost data to %s on /media/backupspot/$BACKUPDIR\n" "$DEVICE"
-tar -czf /media/backupspot/"$BACKUPDIR"/vmhost.tar.gz -- *
-printf "\e[38;2;0;255;0m[+]\e[0m End Backup\n"
+tar --atime-preserve --xattrs --acls --numeric-owner -pczfS /media/backupspot/"$BACKUPDIR"/vmhost.tar.gz -- *
+printf "\e[38;2;0;255;0m[+]\e[0m Cleaning up script\n"
 cleaner
-end
 printf "\e[38;2;0;255;255m [-]\e[0m Updating VMs\n"
-/home/jacob/xentools/updatehost --no-verbose
+domtool schedule update
 ENDTIME="$(date +%s)"
 TOTALTIME=$((ENDTIME-STARTTIME))
 TOTALTIME="$(date -d@$TOTALTIME -u +%H:%M:%S)"
